### ISSUE TITLE
Dependency conflict in requirements.txt

### ISSUE THREAD

**Issue by awright813** [tomhosking/hercules#1]
Get the following message when trying to install requirements in new env:

`ERROR: Cannot install -r requirements.txt (line 1) and -r requirements.txt (line 2) because these package versions have conflicting dependencies.

The conflict is caused by:
    allennlp 2.10.1 depends on transformers<4.21 and >=4.1
    torchseq 2.4.0 depends on transformers==4.24.0`

**Comment by tomhosking** [comment]
Sorry about that - `allennlp` is only needed for generating a particular dataset split. I've removed it from the requirements in 3ad736a58cd025ebe1f5630e298bfbef7130d447. Let me know if you have any other issues.
