### ISSUE TITLE
Issue during model evaluation after setting up the virtual environment.

### ISSUE THREAD

**Issue by ZZabarab** [tomhosking/hercules#3]
Recurring CUDA and GPU version compatibility issues in PyTorch. Can you tell me the CUDA version and Torch version??Recurring CUDA and GPU version compatibility issues in PyTorch. Can you tell me the CUDA version and Torch version??

**Comment by tomhosking** [comment]
Hi, could you please post the full error that you're seeing? The torch version should be `2.0.0`.

**Comment by ZZabarab** [comment]
모델을 학습 시키는 과정에서 
18:19   INFO    CLI     ** Running with config=./models/hercules_space/config.json **
18:19   INFO    CLI     ** Run ID is 20230808_181905_hrq_space_D12K12_HD005_kl25e3_init1_NL005S15_tfidf2_060ratings_hard_smarteval55 **
Traceback (most recent call last):
  File "/home/sh/anaconda3/envs/hercules/bin/torchseq", line 8, in <module>
    sys.exit(main())
  File "/home/sh/anaconda3/envs/hercules/lib/python3.9/site-packages/torchseq/main.py", line 98, in main
    data_loader = dataloader_from_config(config, data_path=args.data_path)
  File "/home/sh/anaconda3/envs/hercules/lib/python3.9/site-packages/torchseq/datasets/builder.py", line 67, in dataloader_from_config
    data_loader = JsonDataLoader(
  File "/home/sh/anaconda3/envs/hercules/lib/python3.9/site-packages/torchseq/datasets/json_loader.py", line 75, in __init__
    raise Exception(
Exception: No splits found for dataset at path ./data/opagg/space-noised/space-25toks-1pronouns-aspects-tfidf2-overlap060-num5-ignorestopwords-enforceratings - 
오류가 발생하는데 경로 지정 및 모델의 경로 지정을 올바릅니다. 어떤 이유인지 알 수 있을까요 ?

**Comment by tomhosking** [comment]
Hi, I made a mistake when zipping up the data files - there is an extra level in the directory structure. Please move the files from:
`./data/opagg/space-noised/space-25toks-1pronouns-aspects-tfidf2-overlap060-num5-ignorestopwords-enforceratings/space-25toks-1pronouns-aspects-tfidf2-overlap060-num5-ignorestopwords-enforceratings` to `./data/opagg/space-noised/space-25toks-1pronouns-aspects-tfidf2-overlap060-num5-ignorestopwords-enforceratings`

**Comment by ZZabarab** [comment]
HI! 훈련 후 평가 과정에서 error가 발생 도움을 줄 수 있나요 ?

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
- 교육 진행 space/amasum data
torchseq --train --reload_after_train --validate --config ./configs/hercules_space.json 
- 교육 후 해당 폴더가 생성됨 
/runs/opagg/20230816_090503_hrq_space_D12K12_HD005_kl25e3_init1_NL005S15_tfidf2_060ratings_hard_smarteval55
- 평가 진행 시 error 발생
torchseq --test --load ./runs/opagg/20230816_172149_hrq_space_D12K12_HD005_kl25e3_init1_NL005S15_tfidf2_060ratings_hard_smarteval55/
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
/home/sh/anaconda3/envs/hercules/lib/python3.9/site-packages/scipy/init.py:132: UserWarning: A NumPy version >=1.21.6 and <1.28.0 is required for this version of SciPy (detected version 1.20.3)
warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
11:25 INFO CLI ** Running with config=./runs/opagg/20230816_172149_hrq_space_D12K12_HD005_kl25e3_init1_NL005S15_tfidf2_060ratings_hard_smarteval55/config.json **
11:25 INFO CLI ** Run ID is 20230817_112508_hrq_space_D12K12_HD005_kl25e3_init1_NL005S15_tfidf2_060ratings_hard_smarteval55_TEST **
11:25 INFO Agent Model will run on GPU-CUDA
11:25 INFO CLI Loading from checkpoint:
11:25 INFO CLI ./runs/opagg/20230816_172149_hrq_space_D12K12_HD005_kl25e3_init1_NL005S15_tfidf2_060ratings_hard_smarteval55/model/checkpoint.pt
11:25 INFO Agent Loading from checkpoint ./runs/opagg/20230816_172149_hrq_space_D12K12_HD005_kl25e3_init1_NL005S15_tfidf2_060ratings_hard_smarteval55/model/checkpoint.pt
11:25 INFO CLI ...loaded!
Traceback (most recent call last):
File "/home/sh/anaconda3/envs/hercules/bin/torchseq", line 8, in
sys.exit(main())
File "/home/sh/anaconda3/envs/hercules/lib/python3.9/site-packages/torchseq/main.py", line 203, in main
if data_loader.test_loader is None:
AttributeError: 'JsonDataLoader' object has no attribute 'test_loader'
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
위는 error 코드입니다.  교육 진행 후 test_loader를 찾을 수 없습니다. 
교육 시 생기지 않습니까?
