### ISSUE TITLE
Issues regarding pip installation and model evaluation

### ISSUE THREAD

**Issue by liuqingli** [tomhosking/hercules#4]
Hi,
I am trying to rerun Hercules from my server but there are two issues:

1. There is a warning message `WARNING: Did not find branch or tag 'a6ebc10', assuming revision or ref.`. Not sure whether it might lead to some potential issues.
2. If we ignore that warning message, the installation seems ok. However, I get an error message `'JsonDataLoader' object has no attribute 'test_loader'` while running `torchseq --test --load ./models/hercules_space/`

Any thoughts regarding this? Thanks very much.

**Comment by tomhosking** [comment]
1. Thanks for letting me know - this should be OK, but I'll update the requirements to avoid this error when I can.
2. It looks like I missed out the test data required to run evaluation this way - if you're just looking to generate the summaries, you can use the example code [here](https://github.com/tomhosking/hercules/blob/main/examples/Space-Eval.ipynb). I'll update the README to make this clear. Thanks!

**Comment by tomhosking** [comment]
These should be fixed by 1e61a389f7d2f468a62c717f17900df6b942c89f
