### ISSUE TITLE
hi       test_loader not find error Q!

### ISSUE THREAD

**Issue by ZZabarab** [tomhosking/hercules#5]
HI! 훈련 후 평가 과정에서 error가 발생 도움을 줄 수 있나요 ?

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

교육 진행 space/amasum data
torchseq --train --reload_after_train --validate --config ./configs/hercules_space.json
교육 후 해당 폴더가 생성됨
/runs/opagg/20230816_090503_hrq_space_D12K12_HD005_kl25e3_init1_NL005S15_tfidf2_060ratings_hard_smarteval55
평가 진행 시 error 발생
torchseq --test --load ./runs/opagg/20230816_172149_hrq_space_D12K12_HD005_kl25e3_init1_NL005S15_tfidf2_060ratings_hard_smarteval55/
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
/home/sh/anaconda3/envs/hercules/lib/python3.9/site-packages/scipy/init.py:132: UserWarning: A NumPy version >=1.21.6 and <1.28.0 is required for this version of SciPy (detected version 1.20.3)
warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
11:25 INFO CLI ** Running with config=./runs/opagg/20230816_172149_hrq_space_D12K12_HD005_kl25e3_init1_NL005S15_tfidf2_060ratings_hard_smarteval55/config.json **
11:25 INFO CLI ** Run ID is 20230817_112508_hrq_space_D12K12_HD005_kl25e3_init1_NL005S15_tfidf2_060ratings_hard_smarteval55_TEST **
11:25 INFO Agent Model will run on GPU-CUDA
11:25 INFO CLI Loading from checkpoint:
11:25 INFO CLI ./runs/opagg/20230816_172149_hrq_space_D12K12_HD005_kl25e3_init1_NL005S15_tfidf2_060ratings_hard_smarteval55/model/checkpoint.pt
11:25 INFO Agent Loading from checkpoint ./runs/opagg/20230816_172149_hrq_space_D12K12_HD005_kl25e3_init1_NL005S15_tfidf2_060ratings_hard_smarteval55/model/checkpoint.pt
11:25 INFO CLI ...loaded!
Traceback (most recent call last):
File "/home/sh/anaconda3/envs/hercules/bin/torchseq", line 8, in
sys.exit(main())
File "/home/sh/anaconda3/envs/hercules/lib/python3.9/site-packages/torchseq/main.py", line 203, in main
if data_loader.test_loader is None:
AttributeError: 'JsonDataLoader' object has no attribute 'test_loader'
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
위는 error 코드입니다. 교육 진행 후 test_loader를 찾을 수 없습니다.
교육 시 생기지 않습니까?

**Comment by tomhosking** [comment]
Hi, if you're trying to generate summaries using a trained model, I'd recommend using the method in [this notebook](https://github.com/tomhosking/hercules/blob/main/examples/Space-Eval.ipynb). I will update the README when I get time.

**Comment by tomhosking** [comment]
1e61a389f7d2f468a62c717f17900df6b942c89f updates readme to remove this eval method
